---
- hosts: webservers
  tasks:
  - name: Installime python-mysqldb
    apt:
       name=python-mysqldb 
       update_cache=yes 
       state=latest

  - name: Loome Kasutaja "Root" parooliga "qwerty" millel on a koik privileegid
    mysql_user:
      name: root
      password: qwerty
      priv: '*.*:ALL,GRANT'
      state: present

  - name: Loome root login faili
    copy:
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
      content: |
          [client]
          user=root 
          password=qwerty

  - name: alglaeme mysql
    service: name=mysql state=restarted
